### ISSUE TITLE
tagfinder not finding (some) tags 

### ISSUE THREAD

**Issue by mnalis** [geometalab/OSMTagFinder#16]
For example,

http://tagfinder.herokuapp.com/search?query=member&lang=en
or
http://tagfinder.herokuapp.com/search?query=membership&lang=en

should in my opinion find:
https://wiki.openstreetmap.org/wiki/Key:membership

But yet, it fails with "Your search - membership - did not match any OpenStreetMap tags."

https://taginfo.openstreetmap.org/keys/membership work normally.

**Comment by sfkeller** [comment]
On Monday, November 21, 2022 6:56 PM @shathor answered to you

Hi Matija Nalis

I’m the co-maintainer of TagFinder. We are always happy to get feedback from users of our little application.
We are currently having issues with our hosting provider allowing updates to our application that’s why its data is unfortunately frozen in the past for now.
The newest data set will also include the recent tags member and membership so it should work for you once we figured out the issue.
It will probably also mean a change of the URL however, but we trying to find a solution that makes the transition seamless for our users.

Kind regards, Simon
