### ISSUE TITLE
Move content to top of page

### ISSUE THREAD

**Issue by danieldegroot2** [geometalab/OSMTagFinder#24]
On the home page, the search box is positioned at the bottom of the page. Possibly also because of the temporary site notice.
It should be positioned at the top of the page in order to be easy to use, noting the empty section above and the search box in the top bar only being available once a search has already been submitted.

There is a similar, smaller empty section above search results.

- **Browser**: Chrome 113.0.5672.127 and older, Edge 113.0.1774.42, Firefox current and older
- **OS**: Windows 10

Screenshots:

![image](https://github.com/geometalab/OSMTagFinder/assets/67521919/1b0964e5-a291-4efd-a8d5-f7fcae7029e0)
![image](https://github.com/geometalab/OSMTagFinder/assets/67521919/b10cb633-7732-4425-b517-b3a6f102877e)

**Comment by shathor** [comment]
Thanks for this report. What browser do you use?

We will soon remove the temporary site notice again and restore the original look hopefully.

**Comment by danieldegroot2** [comment]
> What browser do you use?

Browser and OS are already included above.

**Comment by shathor** [comment]
The redirect alert was reverted and it should now display the original look.

**Comment by shathor** [comment]
The redirect alert was reverted and it should now display the original look.
