### ISSUE TITLE
https://tagfinder.osm.ch/ down (503 Service Unavailable)

### ISSUE THREAD

**Issue by mnalis** [geometalab/OSMTagFinder#25]
https://tagfinder.osm.ch/ fails currently with:

```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.41 (Ubuntu) Server at tagfinder.osm.ch Port 443
```

**Comment by matthijskooijman** [comment]
For anyone running into this that needs the service in the meanwhile, we (from the unrelated meetjestad project) put up an alternative version at https://tagfinder.meetjestad.net/ (for use in our own workshops, but feel free to use it as well). Or you can bring the service up yourself using docker in a few minutes, see #26.

**Comment by sfkeller** [comment]
Thanks for reporting and thanks for the docker file and PR. 
Wer're going to investigate the reason behing this outage, but no promises.

**Comment by shathor** [comment]
The page is available again. External access was blocked by mistake. Thanks for reporting.

**Comment by shathor** [comment]
The page is available again. External access was blocked by mistake. Thanks for reporting.
